"""empty message

Revision ID: 16c5b0d35291
Revises: 12c58d71799a
Create Date: 2025-12-24 05:42:50.474968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c5b0d35291'
down_revision = '12c58d71799a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapats', schema=None) as batch_op:
        batch_op.alter_column('tanggal',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapats', schema=None) as batch_op:
        batch_op.alter_column('tanggal',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
