"""empty message

Revision ID: 58a1e55155c7
Revises: 12c58d71799a
Create Date: 2025-12-17 14:39:21.465124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a1e55155c7'
down_revision = '12c58d71799a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topik', sa.String(length=200), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rapats')
    # ### end Alembic commands ###
