"""add ai_provider to user_settings

Revision ID: dd85287c4fc0
Revises: bdfc9eddd58e
Create Date: 2026-01-30 19:03:38.315551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd85287c4fc0'
down_revision = 'bdfc9eddd58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('ai_provider')

    # ### end Alembic commands ###
